name = "Test"
author = "Fuzz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd474e076f7d61eecfab4437fa6320051a608ae95588e54aba8fa9d33829cc2d"

[versions]
minecraft = "1.21.10"
quilt = "0.29.3-beta.1"

[options]
acceptable-game-versions = ["1.21"]
